name: acumen
description: A new Flutter project.


publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  dio: ^4.0.1



  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
